import 'package:flutter/material.dart';

Color baseColor = _colorFromHex("#F7C04A");
Color bottomTapColor = _colorFromHex("#FEC868");
Color baseRGBColor = _colorFromHex('rgba(255, 226, 85, 0.2)');
Color whiteSmoke = _colorFromHex('#f6f6f6');
Color bottomTap = _colorFromHex('#fffeee');
Color settingBg = _colorFromHex('#F5F5F5');
Color inputBg = _colorFromHex('#F0F0F0');
Color secondColor = _colorFromHex('#f76363');
Color primaryColor = _colorFromHex('#75d6e2');
Color btnBg = _colorFromHex('#F5E7DE');
Color profileBg = _colorFromHex('#D4D4D4');
Color textSecondColor = _colorFromHex('#402E07');
Color grayColor = _colorFromHex('#F1F1F1');
Color borderColorItem = _colorFromHex('#606060');
Color iconColor = _colorFromHex('#030303');
Color placeHolderColor = _colorFromHex('#707070');
Color textStatus = _colorFromHex('#DE6671');
Color deleteColor = _colorFromHex('#D10000');
Color numberColor = _colorFromHex('#EB903F');
Color notificationColor = _colorFromHex('#F84F31');
Color activeColor = _colorFromHex('#BD3C4B');
Color pedingColor = _colorFromHex('#BD3C4B');
Color accepteColor = _colorFromHex('#0081BC');
Color blueRGBcolor = _colorFromHex('rgba(34, 142, 242,0.3)');
Color confrimColor = _colorFromHex('#44C4A1');
Color inActiveColor = _colorFromHex('#111');
Color descriptionColor = _colorFromHex('#737373');
Color borderColor = _colorFromHex('rgba(0,0,0,0.1)');
Color titleColor = _colorFromHex('#040404');
Color subTitleColor = _colorFromHex('#7FABD3');
Color backAbsolute = _colorFromHex('#aba9a680');
Color errorColor = _colorFromHex('#F01F0E');
Color successColor = _colorFromHex('#2AA952');
Color completeColor = _colorFromHex('#D9FFDB');
Color completeTextColor = _colorFromHex('#6FB873');
Color voidColor = _colorFromHex('#FF000040');
Color voidTextColor = _colorFromHex('#FF0000');
Color lightBlue = _colorFromHex('#67C1D5');
Color pointColor = _colorFromHex('#FFC000');
Color requestedColor = _colorFromHex('#FFE5BF');
Color requestedTextColor = _colorFromHex('#FF9900');
Color approvedColor = _colorFromHex('#D9FFDB');
Color approvedTextColor = _colorFromHex('#6FB873');
Color rejectedColor = _colorFromHex('#FECBCB');
Color rejectedTextColor = _colorFromHex('#FF0000');
Color accInactive = _colorFromHex('#FF6464');
Color telegram = _colorFromHex('#0091e2');
Color facebook = _colorFromHex('#0083d8');
Color phoneCall = _colorFromHex('#00a15f');
Color placeholderColor = _colorFromHex('#979797');
Color inProgressColor = _colorFromHex('#0B68F5');
Color payoutColor = _colorFromHex('#FF641B');
Color unsuccessfulColor = _colorFromHex('#2BB36E');
Color delivery = _colorFromHex('#810CA8');
Color greenColor = _colorFromHex('#00BF2D');

Color _colorFromHex(String hexColor) {
  final hexCode = hexColor.replaceAll('#', '');
  return Color(int.parse('FF$hexCode', radix: 16));
}
